# Generated by Django 3.1.3 on 2020-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201129_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
