# Generated by Django 3.1.3 on 2020-11-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')], default=1),
        ),
    ]
